# Math Projects

## Current{-}

### 2-groups in Equivariant Elliptic Cohomology

I got involved in this project thanks to an [MRC Workshop]. 2-groups are
higher categorical variants of groups. The goal of this project is to
find a 2-categorical interpretation of some of naturally occurring
objects (Drinfield double of a group) in mathematical physics and extend
them using ideas from Equivariant Elliptic Cohomology.

### 2-groups in HoTT

I\'m trying to understand how to express and analyze 2-groups in
homotopy type theory. Homotopy type theory is a branch of logic that
encored homotopy equivalences into one of its fundamental axioms thereby
providing a natural formalism for describing homotopy theory.

### Proof Formalization

I am fascinated by the [Lean theorem prover]. More precisely, by the
mathlib community and the work being done toward expanding the existing
library. I taught a course about it at [Mathcamp 2020]. In a group that
includes some students from Mathcamp, we are trying to add [new
mathematical content] to the mathlib library.

## Past

### An application of the h-principle to Manifold Calculus.

This was my PhD thesis, in which I applied homotopy theoretic techniques
to study problems for differential geometry. Here is [the paper] ([arXiv
version]) based on the [thesis] [(Updated on: May 07, 2019)]{.small}.
Here are some notes [notes1], [notes2] from the talks I gave on this
topic.

### Protein folding using Markov chains

During my undergrad, I briefly worked on a project involving some
protein folding models using basic linear algebra.
[Information Processing Letters, IPL4801].

### Projects that did not quite work out

- Spectral lifts of Soergel bimodules, joint with V. Lorman
- Finding loop space structures in exotic Kac-Moody groups
- Equivariant Embedding Calculus

[the paper]: https://doi.org/10.1007/s40062-020-00255-3
{.external-link}
[arXiv version]: https://arxiv.org/abs/1711.07670 {.external-link}
[thesis]: docs/PhD%20Thesis.pdf
[notes1]: docs/2019%20-%20OSU%20Conference.pdf
[notes2]: docs/2019%20-%20Thesis%20Defense.pdf
[Information Processing Letters, IPL4801]: docs/2012%20-%20Protein%20Folding.pdf
[MRC Workshop]: http://www.ams.org/programs/research-communities/2019MRC-Geometry
[Lean theorem prover]: https://leanprover-community.github.io/
[Mathcamp 2020]: https://apurvanakade.github.io/courses/lean_at_MC2020/
[new mathematical content]: https://github.com/apurvnakade/mc2020-projects

