# Recommendation Letters

This section contains advice for people asking for a letter of recommendation from me.

> *It is in your interest to make your letter writer's job as easy as possible.*

I understand that asking for a recommendation letter can be unnerving and daunting. As a student, you might even be unsure as to whether you can ask me for a letter. Please understand that *letter-writing is one of my most important duties*. If you were in any of my classes and received a *good* grade, you are entitled to get rec letters from me. You do not have to have "interacted" with me or "participated" in the lecture in any way.^[Having said that, if I do not know you personally or if you do not provide me enough time/information, my rec letter would be extremely short, just describing your scores in the course.] 

## How to ask for a rec letter

    
  **Timeline:** 
  Please give me as much notice as possible so I can write as detailed a letter as I would like. At least a month is reasonable. Any shorter notice, and you should expect a brief, superficial letter.

  **Email:**
  Send a *formal email request*. 
  Try to include all the information in a single email. 
  If you do not have everything available, just share a folder with the information you have and update it regularly.
  Provide as much information as you think might be relevant. More information is always preferred to less. Here are some common documents to share (drafts are acceptable):

  - A document/email will all the deadlines
  - CV 
  - Unofficial transcripts
  - Statement of Purpose 
  - Program information 
  - Upload instructions

  **Reminders:**
  It's ok to send reminders. In fact, I encourage you to send me a reminder email a week before a deadline.
  Verbal reminders are useless. Send your reminder by email. 

