# Teaching

## Directed Reading Program
The Directed Reading Program is a program for undergrads and grad students/postdocs.
Undergrads are paired with a mentor whose interests align with theirs and they study a topic of their choice for one semester. 
It is intended to help motivated students explore topics in more depth than possible in a classroom setting.
I help organize the [DRP at UWO] and have helped out with organizing the [DRP at JHU].
Following is the list of projects I've mentored.


-   Jacob Fabe, *Fundamental Group* from Topology by Munkres ([DRP, Fall
    2020])
-   Tim Yau, *An Introduction to Manifolds* by Loring Tu. ([DRP, Fall
    2019][DRP, Fall 2020])
-   Hannah Wool, *Topology* by Munkres. ([DRP, Spring 2019])
-   Sydney Timmerman, *Differential Geometry and Lie Groups for
    Physicists* by Marián Fecko. ([DRP, Fall 2018])
-   Eric Cochran, *An Introduction to Manifolds* by Loring Tu. ([DRP,
    Spring 2018])
-   Chris Chia, *The Knot Book* by Adams Collins. ([DRP, Fall 2017])

## Mathcamp

I am fortunate to have been able to participate in the amazing place that is the Mathcamp for the past four years. 
[Canada/USA Mathcamp](https://www.mathcamp.org/) is an immersive summer experience for mathematically talented students ages 13‑18 from all over the world.
Among other things, I have been designing and teaching some fun courses there. 
Following are notes from some of the courses I've taught and projects I've done with mathcampers.

### [![Canada/USA Mathcamp] 2020][2020]

- [Lean at MC2020]
- [How to glue donuts]
- [How Riemann *finally* understood logarithms]

Reading project: Daniel Koizumi, [Riemann Surfaces](https://drive.google.com/file/d/1bv-dCvd4nwfD68RxDeuDFoJ3dZIOoqPq/view) from *Algebraic Curves and Riemann Surfaces* by Rick Miranda.

Lean projects: Kenji, Dedekind Domains in Lean and Michael, Konigsberg Bridge Problem in Lean ([code]).


### [![Canada/USA Mathcamp] 2019][2019]

- [Galois Correspondence of Covering Spaces]
- [From High School Arithmetic to Group Cohomology]
- [Crash Course on Linear Algebra]
- [Riemann Surfaces]

Reading project: Ezra Erives, *Differential Geometry and Lie Groups for Physicists*
    by Marián Fecko.

### [![Canada/USA Mathcamp] 2018][2018]

- [How Curved Is a Potato?]
- [Cohomology via Sheaves]
- [The Quantum
Spring]
- [Would I ever Lie Group to you?]

Reading project: Edgar Wang, *Algebraic Topology* and Alan Yan, *Algebraic Topology* by Hatcher.

### [![Canada/USA Mathcamp] 2017][2017]

- [All things manifoldy]
- [Euler Characteristic]
- [Symmetries of Spaces]
- [What is Homology?]
- [Representation theory]
- [Lagrangian and Hamiltonian Mechanics]

## JHU

At JHU, I designed and taught a full semester (IBL) Honors Single Variable Calculus course twice and also a couple of shorter intersession courses.

- [Honors Single Variable Calculus \'18 (IBL)]
- [Honors Single Variable Calculus \'17 (IBL)]
- [Symmetries & Polynomials \'18 (IBL)]
- [H2G2 Algebraic Topology \'17]

## Expository Notes

Following are some notes I've taken while learning a new subject in my grad school. 
They have not been proofread and are likely to contain several mistakes, viewer discretion is advised.

#### Homotopy Theory

- [ What is a Spectrum? ]
- [ Vector fields on Spheres ]
- [Mosher and Tangora Notes]
- [ Steifel Whitney Numbers ] 
- [Homotopy of  MO]
- [ Model Categories ]
- [Infinity Categories]

#### Symplectic Topology & Physics

- [h-principles MSRI Summer School]
- [Symplectic Geometry]
- [Geometry of Dirac Operators]
- [Finite Group Gauge Theory]
- [FIOs and Lagrangian Submanifolds]
- [Lie Groups]
- [Classical Electromagnetism]

#### Algebra

- [Commutative Algebra Notes]
- [Rep Theory of Symmetric Group]



## Complete List of Courses

| University | Course                                             | Years    | Avg # of students |                             |
|------------|----------------------------------------------------|----------|-------------------|-----------------------------|
| UWO        | Algebraic Topology                                 | 2021     | -                 | Math Grad                   |
|            | Discrete Structures for Engineering                | 2020     | -                 | -                           |
|            | Calculus II for Mathematical and Physical Sciences | 2020     | 150               | First year undergrad        |
|            | Calculus I for Mathematical and Physical Sciences  | 2019     | 176               | First year undergrad        |
|            | Topics in Category Theory                          | 2019     | 3                 | Math Grad                   |
| JHU        | Symmetries & Polynomials                           | 2018     | 10                | All years undergrad         |
|            | Honors Single Variable Calculus                    | 2017, 18 | 7                 | First year undergrad        |
|            | Hitchhiker’s Guide to Algebraic Topology           | 2017     | 11                | All years undergrad         |
|            | Calculus II (For Biology and Social Science)       | 2016     | 5                 | First year undergrad        |
|            | Differential Equations with Applications           | 2015, 17 | 11                | First year undergrad        |
|            | Online Linear Algebra                              | 2014     | 34                | All years undergrad         |
| Mathcamp   | See above                                          | 2015-19  | -                 | High school & middle school |

Course websites: [Calc \'19], [Calc \'20], [DiffEq \'17], [Calc \'16], [DiffEq \'15].

#### Calculus II for Mathematical and Physical Sciences (UWO, Winter 2020)
was a full semester 4 credit course with more than 300 students divided into 2 sections. I was the instructor for one of the sections and was solely responsible for making weekly WebWork homeworks and making exams along with the course coordinator. The class regularly met for 4 hours every week.

#### Calculus I for Mathematical and Physical Sciences (UWO, Fall 2019)
was a full semester course with more than 1000 students divided into 10 sections. I was the instructor for one of the sections and was solely responsible for making weekly WebWork homeworks and in-class quizzes. The class regularly met for 4 hours every week.

#### Topics in Category Theory (UWO, Fall 2019)
was a full semester reading course for math graduate students that I supervised.

#### Calculus II For Biology and Social Science (JHU, Summer 2019)
was a month long summer course which aims to cover semester-worth of material in one month. The class regularly met for 10 hours every week.

#### Differential Equations with Applications
#### Online Linear Algebra


  [DiffEq \'15]: https://drive.google.com/drive/folders/1X7WKPhBljbXt6dBt278t2lKUlWUKIU5Z?usp=sharing
  [Calc \'16]: https://drive.google.com/drive/folders/199dY1MF3TWhJ6gUKQyPf_7YK6rO36HZc?usp=sharing
  [H2G2 Algebraic Topology \'17]: https://drive.google.com/drive/folders/1UmhBnhqXzL1b9kb1zn-7qkYgSSW-Gmwz?usp=sharing
  [DiffEq \'17]: https://drive.google.com/drive/folders/1_lSraXoUwk7CmStg23T1nHpYvf9zq9jA?usp=sharing
  [Honors Single Variable Calculus \'17 (IBL)]: https://drive.google.com/drive/folders/16gJLOf0L6RJ09yRL_b7AozVyq3wHsTMG?usp=sharing
  [Honors Single Variable Calculus \'18 (IBL)]: https://drive.google.com/drive/folders/1xF37VjqpQfSI9W5PmrK19bp8OybGmmpW?usp=sharing
  [Calc \'19]: https://drive.google.com/drive/folders/1HFqAhHYG4m_BtwQSXGeSyItFt1xBHtWE?usp=sharing
  [Calc \'20]: https://drive.google.com/drive/folders/1MkXy0CPOKqSJANr9QSD4gwYdMYjVcdmV?usp=sharing
  [Symmetries & Polynomials \'18 (IBL)]: https://drive.google.com/file/d/1dChuk8J7s31C8xGurzsbf988VORnyXgb/view?usp=sharing

  [Lean at MC2020]: courses/lean_at_MC2020/index.html
  [code]: https://github.com/apurvnakade/mc2020-projects
  [How to glue donuts]: https://drive.google.com/file/d/1iQ_-iqu1x4ueYT4ucNbb_WgAeaf19Ysc/view?usp=sharing
  [How Riemann *finally* understood logarithms]: https://drive.google.com/file/d/1T1iJ2Mw4VupMr9CKs_NriwSWdoPHmMUL/view?usp=sharing

  [Canada/USA Mathcamp]: images/mathcamp-icon.png
  [2020]: https://www.mathcamp.org/2020/index.php 
  [2019]: https://www.mathcamp.org/2019/index.php 
  [2018]: https://www.mathcamp.org/2018/index.php 
  [2017]: https://www.mathcamp.org/2017/index.php 

  [Galois Correspondence of Covering Spaces]: courses/2019MathCamp/GaloisCorrespondenceOfCoveringSpaces.pdf
  [From High School Arithmetic to Group Cohomology]: courses/2019MathCamp/GroupCohomology.pdf
  [Crash Course on Linear Algebra]: courses/2019MathCamp/CrashCourseOnLinearAlgebra.pdf
  [Riemann Surfaces]: courses/2019MathCamp/RiemannSurfaces/index.html
  
  [How Curved Is a Potato?]: courses/2018MathCamp/How%20Curved%20Is%20a%20Potato/
  [Cohomology via Sheaves]: courses/2018MathCamp/CohomologyViaSheaves.pdf
  [The Quantum Spring]: courses/2018MathCamp/TheQuantumSpring.pdf
  [Would I ever Lie Group to you?]: courses/2018MathCamp/WouldIEverLieGroupToYou.pdf
  
  [All things manifoldy]: https://drive.google.com/drive/folders/1_ksj5iK0wjRhCcMH2r3a6t-5Y_IXTG49?usp=sharing
  [Euler Characteristic]: https://drive.google.com/drive/folders/13-oarucRe06Mi7jWdGFAQoW1Z9h0lcWM?usp=sharing
  [Symmetries of Spaces]: https://drive.google.com/drive/folders/18f1YeG10HfZ-keih3sbdkXNTybVcjY38?usp=sharing
  [What is Homology?]: https://drive.google.com/drive/folders/1xardSdDjo__hk7os2CR5BUOPjvAwuD-q?usp=sharing
  [Representation theory]: https://drive.google.com/drive/folders/1gCkxfiQ09TKmofzZKd6TlNikzWV3Ltum?usp=sharing
  [Lagrangian and Hamiltonian Mechanics]: https://drive.google.com/drive/folders/1sCCXN0ffj0SP216WOwTwe7LJgIXJtPpg?usp=sharing

  [What is a Spectrum?]: notes/Bits%20and%20Pieces/What%20is%20a%20Spectrum%3F.pdf
  [Vector fields on Spheres]: notes/CMI/vector%20fields%20on%20spheres/index.html
  [Mosher and Tangora Notes]: notes/JHU%20Course%20Notes/Mosher%20and%20Tangora/index.html
  [Steifel Whitney Numbers]: notes/Bits%20and%20Pieces/SW%20numbers.pdf
  [Model Categories]: notes/Bits%20and%20Pieces/Model%20Categories/index.html
  [Homotopy of MO]: notes/Bits%20and%20Pieces/Homotopy%20of%20MO/index.html
  [Infinity Categories]: notes/JHU%20Course%20Notes/Infinity%20Categories/index.html
  [h-principles MSRI Summer School]: notes/Conference%20Notes/MSRI-h-principles.pdf
  [Symplectic Geometry]: notes/Bits%20and%20Pieces/Symplectic%20Geometry/index.html
  [Geometry of Dirac Operators]: notes/Bits%20and%20Pieces/Geometry%20of%20Dirac%20Operators/index.html
  [Finite Group Gauge Theory]: notes/Bits%20and%20Pieces/Finite%20Gauge%20Group%20Theory/index.html
  [FIOs and Lagrangian Submanifolds]: notes/Bits%20and%20Pieces/FIOs%20and%20Lagrangian%20Submanifolds/index.html
  [Lie Groups]: notes/Bits%20and%20Pieces/Classical%20Lie%20Groups.pdf
  [Classical Electromagnetism]: notes/Bits%20and%20Pieces/Connections%20on%20Principal%20Bundles%20and%20Classical%20Electromagnetism.pdf
  [Commutative Algebra Notes]: notes/JHU%20Course%20Notes/Commutative%20Algebra.pdf
  [Rep Theory of Symmetric Group]: notes/CMI/Representation%20Theory%20of%20Symmetric%20Group.pdf


  [DRP at UWO]: https://www.math.uwo.ca/undergraduate/directed_reading_program.html
  [DRP at JHU]: http://www.math.jhu.edu/drp.html
  [DRP, Fall 2020]: https://www.math.uwo.ca/undergraduate/directed_reading_program.html
  [DRP, Spring 2019]: http://www.math.jhu.edu/drp.html#Spring2019
  [DRP, Fall 2018]: http://www.math.jhu.edu/drp.html#Fall2018
  [DRP, Spring 2018]: http://www.math.jhu.edu/drp.html#Spring2018
  [DRP, Fall 2017]: http://www.math.jhu.edu/drp.html#Fall2017