# Teaching Responsibilities

## Course Instruction

| University | Course                                             | Years             | # of students |                             |
|------------|----------------------------------------------------|-------------------|---------------|-----------------------------|
| UWO        | Algebraic Topology                                 | Winter 2021       | -             | Grad                        |
|            | Discrete Structures for Engineering                | Fall 2020         | -             | First year undergrad        |
|            | Calculus II for Mathematical and Physical Sciences | Winter 2020       | 198           | First year undergrad        |
|            | Calculus I for Mathematical and Physical Sciences  | Fall 2019         | 176           | First year undergrad        |
|            | Topics in Category Theory                          | Fall 2019         | 3             | Grad                        |
| JHU        | Symmetries & Polynomials                           | Intersession 2018 | 15            | All years undergrad         |
|            | Honors Single Variable Calculus                    | Spring 2017, 18   | 7             | First year undergrad        |
|            | Hitchhiker’s Guide to Algebraic Topology           | Intersession 2017 | 11            | All years undergrad         |
|            | Calculus II (For Biology and Social Science)       | Summer 2016       | 5             | First year undergrad        |
|            | Differential Equations with Applications           | Summer 2015, 17   | 11            | First year undergrad        |
|            | Online Linear Algebra                              | Summer 2014       | 34            | All years undergrad         |
| Mathcamp   | Several                                            | Summers 2015-19   | -             | High school & middle school |

Course websites: [Calc \'19], [Calc \'20], [DiffEq \'17], [Calc \'16], [DiffEq \'15].

#### Discrete Structures for Engineering (UWO, Fall 2020) {#discrete-structures-for-engineering-uwo-fall-2020 .unnumbered}

This is a full semester four-credit course offered to second-year
software engineering students. Students are introduced to fundamental
concepts in discrete math, such as logic, combinatorics, modular
arithmetic. Students also learn to write proofs alongside
problem-solving. I am the only instructor for this course, and my class
has nearly 200 students. I had to adapt the course to fit an online mode
of delivery.

#### Calculus II for Mathematical and Physical Sciences (UWO, Winter 2020) {#calculus-ii-for-mathematical-and-physical-sciences-uwo-winter-2020 .unnumbered}

This is a full semester four-credit course offered to all undergraduates
but taken mostly by first-year undergraduates with STEM majors. This is
the second half of a full-year calculus sequence in which students learn
about integration, sequences, and series. This course is a more
challenging variant in which, alongside problem-solving students, are
also taught how to write proofs. The year I taught this course, we had
more than 300 students divided into two sections. I was the instructor
for one of the sections and was solely responsible for making weekly
WebWork homework sets for both the sections and making exams alongside
the course coordinator. The class regularly met for four hours every
week.

#### Calculus I for Mathematical and Physical Sciences (UWO, Fall 2019) {#calculus-i-for-mathematical-and-physical-sciences-uwo-fall-2019 .unnumbered}

This is a full semester four-credit course offered to all undergraduates
but taken mostly by first-year undergraduates from all majors. This is
the first half of a full-year calculus sequence in which students learn
topics such as limits and differentiation. The year I taught this
course, we had more than 1000 students divided into nine sections. I was
the instructor for one of the sections with more than 150 students and
was solely responsible for making weekly WeBWork homework and in-class
quizzes and managing TAs for my section. The class regularly met for
four hours every week.

#### Topics in Category Theory (UWO, Fall 2019) {#topics-in-category-theory-uwo-fall-2019 .unnumbered}

This was a full semester reading course for math graduate students that
I supervised. The students worked through the first chapter of Ravi
Vakil's Foundations of Algebraic Geometry and some chapters from Emily
Riehl's Category Theory in Context. The course was structured in an
open-ended, self-inquiry format. I would assign reading assignments and
meet the students individually every week to discuss their work and
progress.

#### Honors Single Variable Calculus (JHU, Fall 2018, 19) {#honors-single-variable-calculus-jhu-fall-2018-19 .unnumbered}

This is an experimental full semester four-credit course offered at JHU
to first-year undergraduates. The course covers all of the first-year
calculus and introduces students to proof writing. The course is the
only course taught by graduate students. I taught this course for two
semesters, and in both years, I designed the course materials from
scratch. The class size went up from four to ten in the years I taught,
and then close to twenty in the year after. 

#### Calculus II For Biology and Social Science (JHU, Summer 2019) {#calculus-ii-for-biology-and-social-science-jhu-summer-2019 .unnumbered}

This is an accelerated four-credit summer course offered to all
undergraduates but taken mostly by first-year undergraduates and
talented high school students. This course is intended to be taken by
students as their final math course. It introduces them to various
topics such as integration, differential equations, linear algebra,
probability, and statistics. The year I taught, there were 21 students
in the class. I was the only instructor for this course. The class
regularly met for ten hours every week for four weeks and had weekly
exams.

#### Differential Equations with Applications (JHU, Summer 2015, 17) {#differential-equations-with-applications-jhu-summer-2015-17 .unnumbered}

This is an accelerated four-credit summer course offered to all
undergraduates but taken mostly by first-year undergraduates and
talented high school students. In this course, students are taught
various techniques to solve differential equations alongside
applications to other fields. I have taught this course twice. In both
years, I was the only instructor for this course, and there were
approximately four students in the class. The class regularly met for
four hours every week for four weeks and had weekly exams.

#### Intersession courses (JHU, 2017, 2018) {#intersession-courses-jhu-2017-2018 .unnumbered}

These are experimental 2-3 week long 1-2 credit courses offered by any
grad student or faculty at JHU during the winter break. I designed and
taught two IBL-styled courses titled *Hitchhiker's Guide to Algebraic
Topology* and *Symmetries & Polynomials*. These courses were designed to
give non-math majors a preview of some fun topics from Algebraic
Topology and Galois theory. 

#### Online Linear Algebra (JHU, Summer 201four) {#online-linear-algebra-jhu-summer-201four .unnumbered}

This is an accelerated four-credit summer fully online course offered to
all undergraduates but taken mostly by first-year undergraduates and
talented high school students, which covered a semester-worth of
material. I was one of the two instructors for this course, and there
were approximately 90 students in the class.


Innovative Course Development
-----------------------------

### Discrete Structures for Engineering (UWO, Fall 2020) {#sec:discrete-math}

Over the summer, I had to adapt a regular Discrete Math course to an
online asynchronous setting. While I was preparing for the course, my
priority was to reduce student anxiety, simplify the course delivery as
much as possible, and minimize the screen time for students. 

-   **Textbook:** I decided to abandon the traditional textbooks and
    chose an online one, called [Zybooks], which had interactive
    components and provided students with immediate feedback. The book
    is also extremely comprehensive and contains copious amounts of
    auto-graded exercises, in addition to several practice problems,
    which I assign weekly to help keep students on track. Finally, the
    book is exceptionally configurable, both in terms of content and
    structure. The textbook can be found here:
    [learn.zybooks.com/zybook/UWOMath2151ANakadeFall2020][Zybooks]

-   **Lectures:** To minimize the amount of required screen-time for
    students, I made short videos for each topic instead of a long one
    for each lecture. Having a textbook that I knew would fill in the
    gaps left out by the short lectures was crucial for making this
    choice. I embed these video lectures directly within the textbook to
    provide a centralized resource to students, much like other online
    platforms such as Coursera and Kaggle. The video lectures are also
    available on YouTube at the following link:
    [www.youtube.com/playlist?list=PLXAOfwfSuiKm3cL-JftD9ndrjYi7fPcqN]

-   **Exam:** I decided to use [WeBWork] to make exam problems. For
    this, I researched a lot about online testing platforms. I chose
    WeBWork because it is robust and reliable, and it allows for both
    internal randomizations within a question and randomization between
    questions. Having an extensive repository of questions enables me to
    create unique exams for every student.

-   **Summer prep:** With my postdoc advisor and two students' help, we
    designed a repository of several hundred problems for discrete math
    on WeBWork. This repository is easily portable and can be easily
    adapted to any discrete math course. Furthermore, because WebWork is
    open-source this repository can be used by anyone freely. Providing
    cheap and accessible education has always been one of my priorities.

-   **Discussion forums:** I realized early on that communication was
    going to be the key to this course's smooth running. For this
    reason, I choose Piazza as a discussion forum to answer student
    questions and encourage them to answer each other's problems. Piazza
    is very intuitive, easily searchable, and allows for anonymous
    posts. A demo of the discussion forum can be found here:
    [https://piazza.com/demo_login?nid=kd1rr8nxc6z4b5&auth=f76e59e]

-   **Centralized access:** 
    With students getting overwhelmed with the onslaught of online tools, it was necessary to make easily accessible. For this, with a little bit of hacking, I embedded all the above websites onto the school's LMS. 


### Honors Single Variable Calculus (JHU, Fall 2018,19) {#sec:honors-single-variable}

At JHU, I was fortunate to develop and teach Honors Single Variable
Calculus for two semesters. This is an experimental full semester
four-credit course offered at JHU to first-year undergraduates. The
course covers all of the first-year calculus and introduces students to
proof writing.

This is the first course I had to design from scratch. In the years
before mine, the course was mostly taught in a lecture format. I decided
to transition to a fully inquiry-based format. For this, I took the
suggested textbook for this course and converted it into weekly guided
exercises. Because the classes were small, I often dynamically modified
the course material to suit the class. Designing this course gave a
profound insight into the process of student learning and helped me
combat expert blind spots. The materials for this course can be found
here: [apurvanakade.github.io/courses/2018_Honors_Calc/]

### Intersession courses (JHU, Winter 2017,2018) {#sec:intersession}

I taught two week-long intersession courses titled *Hitchhiker's Guide
to Algebraic Topology* and *Symmetries & Polynomials*. I taught both of
these courses in a flipped classroom format. I assigned students guided
exercises, which they solved to learn more about the subject. What was
both challenging and fun was that the students were not math majors, and
so I had to remove all the mathematical jargon and could not even expect
them to know how to write proofs. As such, I had to design my course
around concrete examples and find easily accessible concepts.

For *Hitchhiker's Guide to Algebraic Topology,* I asked the students to
read and present applications of algebraic topology to other fields of
science of their choosing. We had several exciting conversations about
things like applications of knot theory to protein folding and data
science. The notes and the student presentations can be found here:
[apurvanakade.github.io/courses/2017_h2g2_alg_top/index.html]

In the *Symmetries & Polynomials* course, I taught students group theory
using permutations of elements and its connection to Galois theory using
roots of polynomials. During class, I would divide students into groups
of two or three to work on problems together. The problem sets for this
course can be found here:
[drive.google.com/file/d/1dChuk8J7s31C8xGurzsbf988VORnyXgb/view]

  [apurvanakade.github.io/courses/2017_h2g2_alg_top/index.html]: https://apurvanakade.github.io/courses/2017_h2g2_alg_top/index.html
  [drive.google.com/file/d/1dChuk8J7s31C8xGurzsbf988VORnyXgb/view]: https://drive.google.com/file/d/1dChuk8J7s31C8xGurzsbf988VORnyXgb/view

Directed Reading Programs
-------------------------

The Directed Reading Program (DRP) is a program that pairs undergraduate
students with graduate students for one-on-one independent studies over
the course of a semester. The program was started at the University of
Chicago but it is now running in several mathematics departments in the
country. I started as a mentor for the DRP at JHU and then shifted to
being a co-organizer. I also designed and maintained the [website for
the program].

After moving to UWO, with one of my colleagues' help, we started a DRP
chapter here. Our motivation has slowly morphed from getting more
students to major in math to build a thriving and welcoming
undergraduate math community. So far, this program has seen much
interest from undergraduates, and we have seen increased participation
from both the mentor and the mentee sides.

  [website for the program]: http://www.math.jhu.edu/drp.html


Canada/USA Mathcamp
-------------------

I taught at an intensive, residential, five-week summer camp for
mathematically talented high school kids for five summers. The academic
day at the camp is filled with classes, talks, and office hours with
more than 100 courses offered each summer, covering material typically
only encountered in college or grad school. My non-teaching duties
included living in the dorms with students as an RA, being an academic
advisor, and advising students on which courses to take.

-   **Mentor:** I designed and taught week-long courses on advanced
    mathematical topics such as linear algebra, manifolds, Riemann
    surfaces, representation theory, computer-assisted theorem proving,
    and mentored several reading and coding projects. A defining feature
    of Mathcamp is that each student designs their own schedule (with
    the guidance of an academic advisor). As such, the courses need to
    be designed to be both interesting and challenging.

    This year I had the added challenge of doing this online. For this,
    I decided to create a hybrid coding/math course that introduced
    students to computer-assisted theorem proving. For my more
    traditional courses, I taught using Jamboard, which allowed students
    to scroll through the previous pages.

-   **Academic Coordinator:** In the summer of 2017, I was one of the
    two academic coordinators at Mathcamp. The academic coordinators are
    responsible for designing and running all the educational
    activities, including inviting and hosting external visitors,
    preparing a balanced five-week class schedule (more than 100
    classes), assigning (110) students to projects, teaching, and being
    a part of the hiring team.

  [apurvanakade.github.io/courses/2018_Honors_Calc/]: https://apurvanakade.github.io/courses/2018_Honors_Calc/index.html


  [Zybooks]: https://learn.zybooks.com/zybook/UWOMath2151ANakadeFall2020
  [www.youtube.com/playlist?list=PLXAOfwfSuiKm3cL-JftD9ndrjYi7fPcqN]: https://www.youtube.com/playlist?list=PLXAOfwfSuiKm3cL-JftD9ndrjYi7fPcqN
  [WeBWork]: https://webwork.maa.org/
  [piazza.com/class/kd1rr8nxc6zfourb5]: https://piazza.com/class/kd1rr8nxc6zfourb5



  [DiffEq \'15]: https://drive.google.com/drive/folders/1X7WKPhBljbXt6dBt278t2lKUlWUKIU5Z?usp=sharing
  [DiffEq \'17]: https://drive.google.com/drive/folders/1_lSraXoUwk7CmStg23T1nHpYvf9zq9jA?usp=sharing
  [Calc \'16]: https://drive.google.com/drive/folders/199dY1MF3TWhJ6gUKQyPf_7YK6rO36HZc?usp=sharing
  [Calc \'19]: https://www.youtube.com/playlist?list=PLXAOfwfSuiKkdSQB2tVu_KcYMWhZpK19J
  [Calc \'20]: https://drive.google.com/drive/folders/1MkXy0CPOKqSJANr9QSD4gwYdMYjVcdmV?usp=sharing