# Teaching

This page contains several notes from the various courses and projects I've taken, taught, or mentored. 

## Directed Reading Program
The Directed Reading Program is a program for undergrads and grad students/postdocs.
Undergrads are paired with a mentor whose interests align with theirs and they study a topic of their choice for one semester. 
It is intended to help motivated students explore topics in more depth than possible in a classroom setting.
I co-organize the [DRP at UWO] and in the past have co-organized the [DRP at JHU].
Following is the list of projects I've mentored.

-   Jacob Fabe, *Fundamental Group* from Topology by Munkres ([DRP, Fall
    2020])
-   Tim Yau, *An Introduction to Manifolds* by Loring Tu. ([DRP, Fall
    2019][DRP, Fall 2020])
-   Hannah Wool, *Topology* by Munkres. ([DRP, Spring 2019])
-   Sydney Timmerman, [*Differential Geometry and Lie Groups for Physicists*] by Marián Fecko. ([DRP, Fall 2018])
-   Eric Cochran, *An Introduction to Manifolds* by Loring Tu. ([DRP,
    Spring 2018])
-   Chris Chia, *The Knot Book* by Adams Collins. ([DRP, Fall 2017])

## Canada/USA Mathcamp

I am fortunate to have been able to participate in the amazing place that is the Mathcamp for the past four years. 
[Canada/USA Mathcamp](https://www.mathcamp.org/) is an immersive summer experience for mathematically talented students ages 13‑18 from all over the world.
Among other things, I have been designing and teaching some fun courses there. 
Following are notes from some of the courses I've taught and projects I've done with mathcampers.

### [![Canada/USA Mathcamp] 2020][2020]

- [Lean at MC2020]
- [How to glue donuts]
- [How Riemann *finally* understood logarithms]

Reading project: Daniel Koizumi, [Riemann Surfaces](https://drive.google.com/file/d/1bv-dCvd4nwfD68RxDeuDFoJ3dZIOoqPq/view) from *Algebraic Curves and Riemann Surfaces* by Rick Miranda.

Lean projects: Kenji, Dedekind Domains in Lean and Michael, Konigsberg Bridge Problem in Lean ([code]).


### [![Canada/USA Mathcamp] 2019][2019]

- [Galois Correspondence of Covering Spaces]
- [From High School Arithmetic to Group Cohomology]
- [Crash Course on Linear Algebra]
- [Riemann Surfaces]

Reading project: Ezra Erives, *Differential Geometry and Lie Groups for Physicists*
    by Marián Fecko.

### [![Canada/USA Mathcamp] 2018][2018]

- [How Curved Is a Potato?]
- [Cohomology via Sheaves]
- [The Quantum
Spring]
- [Would I ever Lie Group to you?]

Reading project: Edgar Wang, *Algebraic Topology* and Alan Yan, *Algebraic Topology* by Hatcher.

### [![Canada/USA Mathcamp] 2017][2017]

- [All things manifoldy]
- [Euler Characteristic]
- [Symmetries of Spaces]
- [What is Homology?]
- [Representation theory]
- [Lagrangian and Hamiltonian Mechanics]

## Johns Hopkins University

At JHU, I designed and taught a full semester (IBL) Honors Single Variable Calculus course twice and also a couple of shorter intersession courses.

- [Honors Single Variable Calculus \'18 (IBL)]
- [Honors Single Variable Calculus \'17 (IBL)]
- [Symmetries & Polynomials \'18 (IBL)]
- [H2G2 Algebraic Topology \'17]

## Expository Notes

Following are some notes I've taken while learning a new subject in my grad school. 
The entire folder can be found [here](https://drive.google.com/drive/folders/1UR3MW_iRyv6idye57D8QuOu_VEAooS7u?usp=sharing).
They have not been proofread and are likely to contain several mistakes, viewer discretion is advised.
("One day" when I get some free time I intend to clean them up.)

#### Homotopy Theory

- [ What is a Spectrum? ]
- [ Vector fields on Spheres ]
- [Mosher and Tangora Notes]
- [ Steifel Whitney Numbers ] 
- [Homotopy of  MO]
- [ Model Categories ]
- [Infinity Categories]

#### Symplectic Topology & Physics

- [h-principles MSRI Summer School]
- [Symplectic Geometry]
- [Geometry of Dirac Operators]
- [Finite Group Gauge Theory]
- [FIOs and Lagrangian Submanifolds]
- [Classical Lie Groups]
- [Connections on Principal Bundles and Classical Electromagnetism]

#### Algebra

- [Commutative Algebra Notes]
- [Rep Theory of Symmetric Group]


  [H2G2 Algebraic Topology \'17]: https://drive.google.com/drive/folders/1UmhBnhqXzL1b9kb1zn-7qkYgSSW-Gmwz?usp=sharing
  [Honors Single Variable Calculus \'17 (IBL)]: https://drive.google.com/drive/folders/16gJLOf0L6RJ09yRL_b7AozVyq3wHsTMG?usp=sharing
  [Honors Single Variable Calculus \'18 (IBL)]: https://drive.google.com/drive/folders/1xF37VjqpQfSI9W5PmrK19bp8OybGmmpW?usp=sharing
  
  [Symmetries & Polynomials \'18 (IBL)]: https://drive.google.com/file/d/1dChuk8J7s31C8xGurzsbf988VORnyXgb/view?usp=sharing

  [Lean at MC2020]: courses/lean_at_MC2020/index.html
  [code]: https://github.com/apurvnakade/mc2020-projects
  [How to glue donuts]: https://drive.google.com/file/d/1iQ_-iqu1x4ueYT4ucNbb_WgAeaf19Ysc/view?usp=sharing
  [How Riemann *finally* understood logarithms]: https://drive.google.com/file/d/1T1iJ2Mw4VupMr9CKs_NriwSWdoPHmMUL/view?usp=sharing

  [Canada/USA Mathcamp]: images/mathcamp-icon.png
  [2020]: https://www.mathcamp.org/2020/index.php 
  [2019]: https://www.mathcamp.org/2019/index.php 
  [2018]: https://www.mathcamp.org/2018/index.php 
  [2017]: https://www.mathcamp.org/2017/index.php 

  [Galois Correspondence of Covering Spaces]: https://drive.google.com/file/d/1yMpw52rjMrBRj5q8W2PIDRDp9yXmDYVN/view?usp=sharing
  [From High School Arithmetic to Group Cohomology]: https://drive.google.com/file/d/1L7urIOuiu4JIfI6ry2lkKin6Xof8yJdd/view?usp=sharing
  [Crash Course on Linear Algebra]: https://drive.google.com/file/d/1lnX4p_K75vMl0rt0JtOeTYPm9eA6Zi2j/view?usp=sharing
  [Riemann Surfaces]: https://drive.google.com/drive/folders/16o9Slgd4YvhjUCEp_BHSc-xf-2ubKHlo?usp=sharing
  
  [How Curved Is a Potato?]: https://drive.google.com/drive/folders/1zZ49l7ZrmVfg4Lrt7iiCZrk3YH_kVVSg?usp=sharing
  [Cohomology via Sheaves]: https://drive.google.com/file/d/1C21oAC_dH0EX-el2mdT9lH_taY2xZNMm/view?usp=sharing
  [The Quantum Spring]: https://drive.google.com/file/d/1UxZK5drBPLGt4GCC22VtEgYsGLT3p8Nu/view?usp=sharing
  [Would I ever Lie Group to you?]: https://drive.google.com/file/d/1QSPZ5WpFDLCa1AzFrJiE57NXRhwRo8Ra/view?usp=sharing
  
  [All things manifoldy]: https://drive.google.com/drive/folders/1_ksj5iK0wjRhCcMH2r3a6t-5Y_IXTG49?usp=sharing
  [Euler Characteristic]: https://drive.google.com/drive/folders/13-oarucRe06Mi7jWdGFAQoW1Z9h0lcWM?usp=sharing
  [Symmetries of Spaces]: https://drive.google.com/drive/folders/18f1YeG10HfZ-keih3sbdkXNTybVcjY38?usp=sharing
  [What is Homology?]: https://drive.google.com/drive/folders/1xardSdDjo__hk7os2CR5BUOPjvAwuD-q?usp=sharing
  [Representation theory]: https://drive.google.com/drive/folders/1gCkxfiQ09TKmofzZKd6TlNikzWV3Ltum?usp=sharing
  [Lagrangian and Hamiltonian Mechanics]: https://drive.google.com/drive/folders/1sCCXN0ffj0SP216WOwTwe7LJgIXJtPpg?usp=sharing

  [What is a Spectrum?]: https://drive.google.com/file/d/16zRKLkBl4skQ0UNKRXfM7d51qWnBLwGF/view?usp=sharing
  [Vector fields on Spheres]: https://drive.google.com/drive/folders/1fVAeXqn82gOEpEJ9RfBnXqdeJjxTPJNk?usp=sharing
  [Mosher and Tangora Notes]: https://drive.google.com/drive/folders/1vSFBZh3cuDoJPglIeBmLUV1Ur0RvhZ-p?usp=sharing
  [Steifel Whitney Numbers]: https://drive.google.com/file/d/1W9TDU1SaWVLghrSaw8Dg04vdfW9veW_C/view?usp=sharing
  [Model Categories]: https://drive.google.com/drive/folders/1F2cHnX93gMsFYpfASU-TBF4GhZ5TZRBf?usp=sharing
  [Homotopy of MO]: https://drive.google.com/drive/folders/1ns-S54As89Srb8Hlz2ypOmzoOA-CW3il?usp=sharing
  [Infinity Categories]: https://drive.google.com/drive/folders/12tMk47gvY0B8cL0LmtRxLMcrVudd73y-?usp=sharing
  [h-principles MSRI Summer School]: https://drive.google.com/file/d/1uecVJP6Xl1vScsswWGqBtJ1s3o9PwG8C/view?usp=sharing
  [Symplectic Geometry]: https://drive.google.com/drive/folders/1NJllhRgGV5uMSg3hfbp2wcJgScIwhhSZ?usp=sharing
  [Geometry of Dirac Operators]: https://drive.google.com/drive/folders/19GanFw6odpL4tRUJa-mPsVmVKcK52jaW?usp=sharing
  [Finite Group Gauge Theory]: https://drive.google.com/drive/folders/1OyE4ADuxnFIJ3-wuEifCNYWcCF2-iiRd?usp=sharing
  [FIOs and Lagrangian Submanifolds]: https://drive.google.com/drive/folders/1lkx7z7ht5XuRAhhKnhVgLiPHJ2GLSrT3?usp=sharing
  [Lie Groups]: https://drive.google.com/file/d/15SwA8TDmLUMElPQYvhMcIAttXgNzuKbz/view?usp=sharing
  [Connections on Principal Bundles and Classical Electromagnetism]: https://drive.google.com/file/d/1kFh_-_DmR4wt-sDBiOggM5a5U-5W7V_l/view?usp=sharing
  [Commutative Algebra Notes]: https://drive.google.com/file/d/1iwjYv6a5myfnvFKXg8VGAd2fsMZTDXin/view?usp=sharing
  [Rep Theory of Symmetric Group]: https://drive.google.com/file/d/1xMliaDffPi6yUzp5U2d_wIdPJ6yyfLE1/view?usp=sharing

  [*Differential Geometry and Lie Groups for Physicists*]: http://www.math.jhu.edu/drpfiles/F2018%20-%20Sydney.pdf
  [DRP at UWO]: https://www.math.uwo.ca/undergraduate/directed_reading_program.html
  [DRP at JHU]: http://www.math.jhu.edu/drp.html
  [DRP, Fall 2020]: https://www.math.uwo.ca/undergraduate/directed_reading_program.html
  [DRP, Spring 2019]: http://www.math.jhu.edu/drp.html#Spring2019
  [DRP, Fall 2018]: http://www.math.jhu.edu/drp.html#Fall2018
  [DRP, Spring 2018]: http://www.math.jhu.edu/drp.html#Spring2018
  [DRP, Fall 2017]: http://www.math.jhu.edu/drp.html#Fall2017

  [*Foundations of Algebraic Geometry*]: http://math.stanford.edu/~vakil/216blog/FOAGnov1817public.pdf
  [*Category Theory in Context*]: http://www.math.jhu.edu/~eriehl/context.pdf
