# Research {-}

My research is in the area of algebraic topology and homotopy theory. My broad
interests are in understanding how homotopy theoretic tools can be used
to solve problems from other areas of math.

### String structures, 2-group bundles, and a categorification of the Freed-Quinn line bundle {-}

[ArXiv preprint](https://arxiv.org/abs/2110.07571)

I got involved in this project thanks to the [MRC Workshop](http://www.ams.org/programs/research-communities/2019MRC-Geometry).
2-groups are higher categorical variants of groups.
In this project, we provide a 2-categorical interpretation of some of naturally occurring objects (Drinfield double of a group) in mathematical physics and extend them using ideas from Equivariant Elliptic Cohomology. This is a joint work with Daniel Berwick-Evans, Emily Cliff, Laura Murray, and Emma Phillips.

### PhD thesis: An application of the $h$-principle to Manifold Calculus {-}

[Paper in *Journal of Homotopy and Related Structures*](https://doi.org/10.1007/s40062-020-00255-3) <br/>
[ArXiv preprint](https://arxiv.org/abs/1711.07670) <br/>
[Original Thesis](https://github.com/apurvnakade/PDFs/blob/main/assorted%20notes/Research/PhD%20Thesis.pdf) <br/>
[Notes from a talk](https://github.com/apurvnakade/PDFs/blob/main/assorted%20notes/Research/2019%20-%20OSU%20Conference.pdf) <br/>
[Thesis defense presentation](https://github.com/apurvnakade/PDFs/blob/main/assorted%20notes/Research/2019%20-%20Thesis%20Defense.pdf)

In my PhD thesis, I applied homotopy theoretic techniques to study problems for differential geometry. 
I showed that the technique of manifold calculus cannot be used to analyze the space of isosymplectic embeddings of symplectic manifolds.
This thesis also provides a broad class of examples of non-analytic embedding functors (in the sense of manifold calculus).

### Protein folding using Markov chains {-}

[Paper in Information Processing Letters, IPL4801](https://github.com/apurvnakade/PDFs/blob/main/assorted%20notes/Research/2012%20-%20Protein%20Folding.pdf)

During my undergrad, I briefly worked on a project analyzing a Markov chain model of protein folding. We showed that the mixing time of the Metropolis algorithm is not a decreasing function of the value of gap between the lowest and the second lowest energies.
This is joint work with Somenath Biswas.

### Projects that did not quite work out {-}

- 2-groups in HoTT
- Spectral lifts of Soergel bimodules, joint with V. Lorman
- Finding loop space structures in exotic Kac-Moody groups
- Equivariant Embedding Calculus
