project:
  type: website
  output-dir: docs

website:
  title: "Apurva Nakade"
  navbar:
    left:
      - text: Home
        href: https://apurvanakade.github.io/
      - notes.qmd
      - text: Scribbles
        href: https://apurvanakade.github.io/scribbles/
      - CV.qmd
    right:
      - icon: github
        href: https://github.com/apurvanakade/
        aria-label: GitHub
  # sidebar: 
  #   style: floating
  #   search: true
  #   contents: auto
  open-graph: true
  site-url: https://apurvanakade.github.io/
  repo-url: https://github.com/apurvanakade/apurvanakade.github.io/
  search:
    type: overlay
    location: navbar
  

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css

output-dir: docs