[book]
authors = ["Apurva Nakade"]
language = "en"
multilingual = false
src = "src"
title = "Apurva Nakade"

[output.html]
additional-css = ["theme/css/tufte.css"]
copy-fonts = false

[output.html.print]
enable = false

[output.html.fold]
enable = false 
level = 1 
