[book]
authors = ["Apurva Nakade"]
language = "en"
multilingual = false
src = "src"
title = "Apurva Nakade"

[output.html]
mathjax-support = true
additional-css = ["css/custom.css"]
additional-js = ["js/custom.js"]
no-section-label = true
git-repository-url = "https://github.com/apurvnakade"
git-repository-icon = "fa-github"
site-url = "https://apurvanakade.github.io/"


[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = false
copy-js = true
line-numbers = true