---
title: Recommendation Letters
date: 2023-09-24 15:17:32
toc: false
---

source: [https://www.hmc.edu/mathematics/wp-content/uploads/sites/49/2020/03/recommendation-letters.pdf](https://www.hmc.edu/mathematics/wp-content/uploads/sites/49/2020/03/recommendation-letters.pdf)



If I have recently agreed to write any recommendation letters for you, then at
least two weeks before the first letter is due, please email me
• a copy of your personal statement (if applicable),
• an unofficial copy of your transcript, and
• a copy of your resume.
In the same email, please send me your answers to the following questions:
1. What is your name, graduation year, and major?
2. For what are you applying (e.g., graduate school)? List the programs to
which you are applying, together with due dates.
3. How long have I known you (in years and months), and what is my relationship to you (e.g., instructor, research advisor, etc.)?
4. For what classes have I had you, what final grades did I assign you, and
how did you distinguish yourself in my classes?
5. How would you describe yourself? What are your strengths? What are
your weaknesses? Your response to this question is important to me, so
the more details the better.
6. What are some of your academic and nonacademic accomplishments?
7. What makes me particularly qualified to write a letter for you?
8. What makes you particularly qualified for this position/honor/award?
9. What are your long term goals and will this position/honor/award help?
If so, how?
10. Additional comments (summer research, interesting jobs, hobbies, etc.)?
Finally, please send me email reminders as deadlines approach, and feel free
to chat with me about other ways you can make the application process go
smoothly. Good luck!
Michael Orrison
Professor of Mathematics
Harvey Mudd College