## Teaching

[Teaching Evaluations](https://github.com/apurvanakade/PDFs/tree/main/teaching%20evaluations)

### Instructor, JHU AMS

#### Summer 2026

- Foundational Mathematics of Artificial Intelligence, Summer 2026
- Intermediate Probability and Statistics, Summer 2026

#### Spring 2026

- Intro to Computational Math, Spring 2026
- Discrete Math, Spring 2026
- Monte Carlo Methods, Spring 2026

#### Fall 2025

- Monte Carlo Methods, Fall 2025
- Discrete Math, Fall 2025

#### Summer 2025

- Foundational Mathematics of Artificial Intelligence, Summer 2025
- Intermediate Probability and Statistics, Summer 2025

#### Spring 2025

- Discrete Math, Spring 2025
- Monte Carlo Methods, Spring 2025
- Honors Algebra II, Spring 2025
- Intermediate Probability and Statistics, Spring 2025

#### Fall 2024

- Discrete Math, Fall 2024
- Monte Carlo Methods, Fall 2024
- Honors Algebra II, Fall 2024

#### Summer 2024

- Engineering Innovation, Summer 2024

#### Spring 2024

- Graph Theory, Spring 2024
- Linear Algebra and Differential Equations, Spring 2024
- Honors Algebra II, Spring 2024

#### Fall 2023

- Discrete Math, Fall 2023

### Instructor, Northwestern

- Elementary Differential Equations, Spring 2023
- Foundations of Higher Mathematics, Winter 2023
- MENU Linear Algebra and Multivariable Calculus (Coordinator), 2022-23
- Introduction to Optimization, Winter, Spring 2022
- MENU Linear Algebra and Multivariable Calculus, 2021-22
- Single-Variable Differential Calculus, Fall 2021

### Instructor, UWO

- Algebraic Topology (graduate level), Winter 2021
- Topology Bootcamp, Fall 2020
- Discrete Structures for Engineering, Fall 2020
- Calculus II for Mathematical and Physical Sciences, Winter 2020
- Calculus I for Mathematical and Physical Sciences, Fall 2019
- Topics in Category Theory, Fall 2019

### Instructor, JHU

- Honors Single Variable Calculus, Fall 2018, 2017
- Symmetries & Polynomials, Intersession 2018
- Hitchhikers Guide to Algebraic Topology, Intersession 2017
- Differential Equations with Applications, Summer 2017, 2015
- Online Linear Algebra, Summer 2014

### Instructor, Canada/USA Mathcamp

- How to Discover the Bell Curve, Summer 2026
- Theorem Proving in Lean, Summer 2020
- Galois Correspondence of Covering Spaces, Summer 2019
- From High School Arithmetic to Group Cohomology, Summer 2019
- Riemann Surfaces, Summer 2019
- Crash Course on Linear Algebra, Summer 2018
- How Curved Is a Potato?, Summer 2018
- Would I Ever Lie Group to You?, Summer 2018
- Cohomology via Sheaves, Summer 2018
