#!/usr/bin/env python3
"""AI-owned one-shot generator for the SVG cover images used by project cards.

    python3 _scripts/make_covers.py

Two kinds of output, both written to images/projects/ and committed (they are
not part of the Quarto build):

  * real figures  -- an actual drawing of the mathematics the project is about,
    generated by the functions in FIGURES;
  * typographic covers -- for projects with no natural figure, from COVERS.

Everything is drawn on an 800x500 canvas. Cards crop with object-fit: cover and
the crop aspect swings from about 0.95 (a three-column grid on a narrow screen)
to about 2.2 (the home page card), so only x in [162, 638] and y in [68, 432]
survive every case. Figures are centred inside that band -- see CLAUDE.md.

These figures replace hot-linked Wikimedia images, which broke on the published
site. Being local they also cannot change or disappear underneath us.
"""
import math
import pathlib

OUT = pathlib.Path(__file__).resolve().parent.parent / "images" / "projects"

TPL = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500" role="img" aria-label="{alt}">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="{c1}"/><stop offset="100%" stop-color="{c2}"/>
    </linearGradient>
  </defs>
  <rect width="800" height="500" fill="url(#g)"/>
  <g fill="none" stroke="#ffffff" stroke-opacity="0.16" stroke-width="1.5">{deco}</g>
  <text x="400" y="{ky}" text-anchor="middle" font-family="Inter, Helvetica, Arial, sans-serif"
        font-size="20" font-weight="500" fill="#ffffff" fill-opacity="0.72"
        letter-spacing="2.5">{kicker}</text>
  <text x="400" y="{ty}" text-anchor="middle" font-family="Inter, Helvetica, Arial, sans-serif"
        font-size="{fs}" font-weight="600" fill="#ffffff" letter-spacing="-1">{lines}</text>
</svg>
"""

def esc(t):
    return t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def tspans(title, fs):
    words, lines, cur = title.split(), [], ""
    for w in words:
        if len(cur + " " + w) > 15 and cur:
            lines.append(cur); cur = w
        else:
            cur = (cur + " " + w).strip()
    lines.append(cur)
    return "".join(
        f'<tspan x="400" dy="{0 if i == 0 else fs * 1.15}">{esc(l)}</tspan>'
        for i, l in enumerate(lines)
    ), len(lines)

GRID = "".join(f'<path d="M{x} 0 V500"/>' for x in range(80, 800, 80))
DOTS = "".join(
    f'<circle cx="{x}" cy="{y}" r="3"/>'
    for x in range(90, 800, 70) for y in range(60, 400, 70)
)
WAVE = "".join(
    f'<path d="M0 {y} Q200 {y-60} 400 {y} T800 {y}"/>' for y in range(90, 520, 55)
)

COVERS = [
    ("visual-math-lab",      "Visual Math Lab",           "INTERACTIVE VISUALIZATION", "#0f5f6a", "#123c52", WAVE),
    ("ams-course-explorer",  "AMS Course Explorer",       "COURSE MAP",                "#1c4f7c", "#16324f", GRID),
    ("lean-formalization",   "Formalizing Math in Lean",  "PROOF ASSISTANT",           "#3b3663", "#231f3f", DOTS),
    ("oer-linear-algebra",   "Open Textbook, Linear Algebra", "OER",                   "#6b4226", "#3f2716", GRID),
    ("expository-notes",     "Expository Notes",          "ASSORTED WRITING",          "#2f4a3f", "#1c2e28", DOTS),
    ("mathcamp-assorted",    "More Mathcamp Classes",     "CANADA/USA MATHCAMP",       "#7a3b52", "#43202e", WAVE),
    ("intro-to-optimization", "Introduction to Optimization", "LINEAR PROGRAMMING",     "#14535e", "#0e3038", GRID),
    ("discrete-math-online", "Discrete Math, Asynchronous", "COURSE DESIGN",            "#4a3a70", "#26203c", DOTS),
    ("group-cohomology",     "Arithmetic to Group Cohomology", "EXACT SEQUENCES",       "#5c3f2a", "#33221a", GRID),
    ("symmetries-and-polynomials", "Symmetries & Polynomials", "GALOIS THEORY",         "#2d4a63", "#1a2c3c", WAVE),
    ("theorem-proving-lean", "Theorem Proving in Lean",   "MATHCAMP",                  "#334066", "#1d2440", DOTS),
]

def monte_carlo():
    """A real figure rather than a typographic cover: the Monte Carlo estimate of
    pi, as points scattered over a square with an inscribed quarter circle.

    This replaces a 13.5 MB animated GIF that was hot-linked from Wikimedia --
    far too heavy for a card thumbnail, and it visibly failed to load. Generated
    here so it is small, on-palette, and ours.
    """
    import math
    import random

    rng = random.Random(20260907)          # fixed seed: regenerating is a no-op
    W, H = 800, 500
    side = 300                             # plot square, kept inside the crop band
    x0, y0 = 70, (H - side) / 2

    inside, outside = [], []
    for _ in range(1100):
        u, v = rng.random(), rng.random()
        pt = f'<circle cx="{x0 + u * side:.1f}" cy="{y0 + side - v * side:.1f}" r="2.4"/>'
        (inside if u * u + v * v <= 1 else outside).append(pt)

    n_in, n_all = len(inside), len(inside) + len(outside)
    est = 4 * n_in / n_all
    tx = x0 + side + 55                    # text column, right of the scatter
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" role="img"
     aria-label="Monte Carlo estimate of pi: {n_in} of {n_all} random points fall inside the quarter circle">
  <defs>
    <linearGradient id="mc" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#123c52"/><stop offset="100%" stop-color="#0d2a3a"/>
    </linearGradient>
  </defs>
  <rect width="{W}" height="{H}" fill="url(#mc)"/>
  <rect x="{x0}" y="{y0}" width="{side}" height="{side}" fill="none"
        stroke="#ffffff" stroke-opacity="0.25"/>
  <path d="M{x0} {y0} A {side} {side} 0 0 1 {x0 + side} {y0 + side}"
        fill="none" stroke="#ffffff" stroke-opacity="0.5" stroke-width="2"/>
  <g fill="#f2b880" fill-opacity="0.95">{''.join(inside)}</g>
  <g fill="#ffffff" fill-opacity="0.30">{''.join(outside)}</g>
  <text x="{tx}" y="{H / 2 - 42}" font-family="Inter, Helvetica, Arial, sans-serif"
        font-size="20" font-weight="500" fill="#ffffff" fill-opacity="0.62"
        letter-spacing="2.5">MONTE CARLO</text>
  <text x="{tx}" y="{H / 2 + 14}" font-family="Inter, Helvetica, Arial, sans-serif"
        font-size="46" font-weight="600" fill="#ffffff" letter-spacing="-1">&#960; &#8776; {est:.3f}</text>
  <text x="{tx}" y="{H / 2 + 52}" font-family="Inter, Helvetica, Arial, sans-serif"
        font-size="21" fill="#ffffff" fill-opacity="0.62">4 &#215; {n_in}/{n_all}</text>
</svg>
"""


# ---------------------------------------------------------------------------
# Real figures
#
# Shared geometry: every figure is centred on (CX, CY) and kept inside the
# crop-safe band documented at the top of this file. Labels sit below the
# drawing, still inside the band.
# ---------------------------------------------------------------------------

CX, CY = 400, 212          # centre of the drawing
LABEL_Y, SUB_Y = 372, 406  # baselines for the kicker and the sub-label
SANS = "Inter, Helvetica, Arial, sans-serif"


def frame(body, alt, c1, c2, kicker, sub=""):
    """Wrap a drawing in the standard gradient panel plus centred captions."""
    sub_el = (
        f'<text x="{CX}" y="{SUB_Y}" text-anchor="middle" font-family="{SANS}" '
        f'font-size="21" fill="#ffffff" fill-opacity="0.62">{sub}</text>'
        if sub else ""
    )
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500" role="img" aria-label="{esc(alt)}">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="{c1}"/><stop offset="100%" stop-color="{c2}"/>
    </linearGradient>
  </defs>
  <rect width="800" height="500" fill="url(#g)"/>
  {body}
  <text x="{CX}" y="{LABEL_Y}" text-anchor="middle" font-family="{SANS}"
        font-size="20" font-weight="500" fill="#ffffff" fill-opacity="0.70"
        letter-spacing="2.5">{esc(kicker)}</text>
  {sub_el}
</svg>
"""


def polyline(pts, stroke="#ffffff", width=2.4, opacity=1.0, fill="none"):
    d = "M" + " L".join(f"{x:.1f} {y:.1f}" for x, y in pts)
    return (f'<path d="{d}" fill="{fill}" stroke="{stroke}" stroke-width="{width}" '
            f'stroke-opacity="{opacity}" stroke-linecap="round" stroke-linejoin="round"/>')


def fit(pts, half_w, half_h):
    """Scale/translate projected points to sit centred on (CX, CY)."""
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    sx = (max(xs) - min(xs)) or 1.0
    sy = (max(ys) - min(ys)) or 1.0
    k = min(2 * half_w / sx, 2 * half_h / sy)
    mx, my = (min(xs) + max(xs)) / 2, (min(ys) + max(ys)) / 2
    return lambda p: (CX + (p[0] - mx) * k, CY + (p[1] - my) * k)


ACCENT = "#f2b880"


def winding_number():
    """A closed curve that winds twice around the marked point: the winding
    number, which is where a first algebraic-topology course starts."""
    T = 4 * math.pi                       # two full turns
    pts = []
    for i in range(1201):
        t = T * i / 1200
        r = 0.70 + 0.38 * t / T
        pts.append((r * math.cos(t), r * math.sin(t)))
    pts.append(pts[0])                    # close it with a radial segment, which
                                          # crosses the spiral once and visibly
                                          # makes the curve a single closed loop
    f = fit(pts + [(0, 0)], 150, 118)
    curve = [f(p) for p in pts]
    ox, oy = f((0, 0))
    body = (
        polyline(curve, "#ffffff", 2.6, 0.92)
        + f'<circle cx="{ox:.1f}" cy="{oy:.1f}" r="6" fill="{ACCENT}"/>'
        + f'<circle cx="{ox:.1f}" cy="{oy:.1f}" r="15" fill="none" stroke="{ACCENT}" '
          f'stroke-opacity="0.45" stroke-width="1.5"/>'
    )
    return frame(body, "A closed curve winding twice around a point",
                 "#123c52", "#0d2a3a", "WINDING NUMBER", "n = 2")


def weierstrass():
    """The Weierstrass function: continuous everywhere, differentiable nowhere.
    The example that makes an honours calculus course worth taking."""
    def w(x):
        return sum(0.5 ** n * math.cos(3 ** n * math.pi * x) for n in range(8))
    N = 3000
    pts = [(-2 + 4 * i / N, w(-2 + 4 * i / N)) for i in range(N + 1)]
    f = fit(pts, 168, 96)
    body = (
        f'<path d="M{CX - 175} {CY} H{CX + 175}" stroke="#ffffff" stroke-opacity="0.18" stroke-width="1"/>'
        + polyline([f(p) for p in pts], ACCENT, 1.5, 0.95)
    )
    return frame(body, "The Weierstrass function, continuous but nowhere differentiable",
                 "#1a2c3c", "#101d28", "WEIERSTRASS FUNCTION",
                 "continuous, nowhere differentiable")


def penrose():
    """The Penrose tribar -- three bars of cubes running along the x, y and z
    axes. In isometric projection the lattice point (n, n, n) lands exactly on
    (0, 0, 0), so the far end of the third bar closes onto the start of the
    first and the figure reads as impossible. It is the standard example of a
    class that is locally trivial but globally non-trivial, which is what sheaf
    cohomology measures."""
    L, w = 5.0, 1.0

    def iso(p):
        i, j, k = p
        return ((i - j) * 0.8660254, (i + j) * 0.5 - k)

    # (corner, extent) for the three bars, laid out on the cube lattice
    bars = [
        ((0.0, 0.0, 0.0), (L, w, w)),          # along +x
        ((L - w, w, 0.0), (w, L - w, w)),      # along +y
        ((L - w, L - w, w), (w, w, L - w)),    # along +z
    ]
    corners = []
    for (ox, oy, oz), (dx, dy, dz) in bars:
        for a in (0, 1):
            for b in (0, 1):
                for c in (0, 1):
                    corners.append((ox + a * dx, oy + b * dy, oz + c * dz))
    f = fit([iso(p) for p in corners], 140, 120)

    def face(pts):
        return [f(iso(p)) for p in pts]

    shades = ("#ffffff", "#cfe3ea", "#8fb3c4")
    out = []
    # Draw the +z bar first and the +x bar last: at the impossible joint the
    # near bar must paint over the far one.
    for (ox, oy, oz), (dx, dy, dz) in reversed(bars):
        x1, y1, z1 = ox + dx, oy + dy, oz + dz
        faces = [
            [(x1, oy, oz), (x1, y1, oz), (x1, y1, z1), (x1, oy, z1)],   # +x
            [(ox, y1, oz), (x1, y1, oz), (x1, y1, z1), (ox, y1, z1)],   # +y
            [(ox, oy, z1), (x1, oy, z1), (x1, y1, z1), (ox, y1, z1)],   # +z
        ]
        for shade, quad in zip(shades, faces):
            pts = face(quad)
            d = "M" + " L".join(f"{x:.1f} {y:.1f}" for x, y in pts) + " Z"
            out.append(f'<path d="{d}" fill="{shade}" fill-opacity="0.92" '
                       f'stroke="#0d2a3a" stroke-width="2" stroke-linejoin="round"/>')
    return frame("".join(out), "The Penrose impossible tribar",
                 "#2f4a3f", "#16261f", "SHEAF COHOMOLOGY",
                 "locally consistent, globally impossible")


def trefoil():
    """A trefoil knot from its 3D parametrisation. z = -sin(3t) vanishes at the
    six points t = k*pi/3, so those cut the curve into arcs that are each wholly
    above or wholly below the crossings. Casing whole arcs (rather than
    individual segments, whose casings overwrite their neighbours) resolves the
    over- and under-strands correctly."""
    def at(t):
        return (math.sin(t) + 2 * math.sin(2 * t),
                math.cos(t) - 2 * math.cos(2 * t),
                -math.sin(3 * t))

    arcs, M, pad = [], 150, 0.05
    for k in range(6):
        t0, t1 = k * math.pi / 3 - pad, (k + 1) * math.pi / 3 + pad
        arcs.append([at(t0 + (t1 - t0) * i / M) for i in range(M + 1)])

    f = fit([(q[0], q[1]) for a in arcs for q in a], 138, 118)
    out = []
    for arc in sorted(arcs, key=lambda a: sum(q[2] for q in a) / len(a)):
        pts = [f((q[0], q[1])) for q in arc]
        out.append(polyline(pts, "#12202b", 17, 1.0))   # casing cuts the strand behind
        out.append(polyline(pts, ACCENT, 7, 1.0))
    return frame("".join(out), "A trefoil knot diagram",
                 "#1b3140", "#12202b", "KNOTS AND SPACES", "the trefoil")


def icosahedron():
    """A rotated icosahedron: 12 vertices, 30 edges, and the symmetry group
    that makes it a standing example in a course on groups."""
    phi = (1 + 5 ** 0.5) / 2
    verts = []
    for s1 in (-1, 1):
        for s2 in (-1, 1):
            verts += [(0, s1, s2 * phi), (s1, s2 * phi, 0), (s2 * phi, 0, s1)]
    verts = sorted(set(verts))
    edges = []
    for a in range(len(verts)):
        for b in range(a + 1, len(verts)):
            d = sum((verts[a][k] - verts[b][k]) ** 2 for k in range(3))
            if abs(d - 4) < 1e-6:
                edges.append((a, b))
    ax, ay = 0.55, 0.42
    rot = []
    for x, y, z in verts:
        y, z = y * math.cos(ax) - z * math.sin(ax), y * math.sin(ax) + z * math.cos(ax)
        x, z = x * math.cos(ay) + z * math.sin(ay), -x * math.sin(ay) + z * math.cos(ay)
        rot.append((x, y, z))
    f = fit([(p[0], p[1]) for p in rot], 128, 118)
    proj = [f((p[0], p[1])) for p in rot]
    out = []
    for a, b in sorted(edges, key=lambda e: (rot[e[0]][2] + rot[e[1]][2]) / 2):
        near = (rot[a][2] + rot[b][2]) / 2 > 0
        out.append(polyline([proj[a], proj[b]], "#ffffff",
                            2.4 if near else 1.4, 0.95 if near else 0.30))
    for (x, y), v in zip(proj, rot):
        if v[2] > 0:
            out.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="4" fill="{ACCENT}"/>')
    return frame("".join(out), "An icosahedron wireframe",
                 "#3b3663", "#211d3a", "SYMMETRY GROUPS", "the icosahedron")


def riemann_sqrt():
    """The Riemann surface of the square root, drawn as the graph of Re(w) over
    z = w^2: the sheet that has to pass through itself because the square root
    needs two of them."""
    def pt(rho, th):
        z_re = rho * rho * math.cos(2 * th)
        z_im = rho * rho * math.sin(2 * th)
        h = rho * math.cos(th)
        return (z_re - 0.5 * z_im, -1.05 * h + 0.42 * z_im)

    curves = []
    for n in range(9):                       # constant rho
        rho = 0.22 + 0.78 * n / 8
        curves.append(([pt(rho, 2 * math.pi * i / 220) for i in range(221)], 0.55))
    for n in range(24):                      # constant theta
        th = 2 * math.pi * n / 24
        curves.append(([pt(0.16 + 0.84 * i / 40, th) for i in range(41)], 0.30))
    f = fit([p for c, _ in curves for p in c], 150, 118)
    body = "".join(polyline([f(p) for p in c], "#ffffff", 1.5, op) for c, op in curves)
    return frame(body, "The Riemann surface of the square root",
                 "#14535e", "#0b2a30", "RIEMANN SURFACES", "the square root, two sheets")


def potato():
    """A closed curve with its osculating circle at the point of highest
    curvature -- the honest answer to how curved a potato is."""
    def r(t):
        return 1 + 0.16 * math.cos(2 * t + 0.7) + 0.09 * math.cos(3 * t - 1.1) \
                 + 0.05 * math.cos(5 * t + 0.3)
    N = 720
    raw = [(r(2 * math.pi * i / N) * math.cos(2 * math.pi * i / N),
            r(2 * math.pi * i / N) * math.sin(2 * math.pi * i / N)) for i in range(N + 1)]
    f = fit(raw, 132, 112)
    pts = [f(p) for p in raw]

    # discrete curvature from the circumradius of three consecutive samples
    best, best_k = 0, 0.0
    for i in range(4, N - 4, 2):
        (x1, y1), (x2, y2), (x3, y3) = pts[i - 4], pts[i], pts[i + 4]
        a = math.dist((x1, y1), (x2, y2)); b = math.dist((x2, y2), (x3, y3))
        c = math.dist((x1, y1), (x3, y3))
        area = abs((x2 - x1) * (y3 - y1) - (x3 - x1) * (y2 - y1)) / 2
        if area > 1e-9:
            k = 4 * area / (a * b * c)
            if k > best_k:
                best_k, best = k, i
    px, py = pts[best]
    ax_, ay_ = pts[best - 4]; bx, by = pts[best + 4]
    tx, ty = bx - ax_, by - ay_
    n = math.hypot(tx, ty) or 1
    nx, ny = -ty / n, tx / n
    cxx, cyy = CX - px, CY - py                     # inward test
    if nx * cxx + ny * cyy < 0:
        nx, ny = -nx, -ny
    R = 1 / best_k
    body = (
        polyline(pts, "#ffffff", 2.6, 0.9, fill="rgba(255,255,255,0.06)")
        + f'<circle cx="{px + nx * R:.1f}" cy="{py + ny * R:.1f}" r="{R:.1f}" fill="none" '
          f'stroke="{ACCENT}" stroke-opacity="0.75" stroke-width="2" stroke-dasharray="5 5"/>'
        + f'<circle cx="{px:.1f}" cy="{py:.1f}" r="5" fill="{ACCENT}"/>'
    )
    return frame(body, "A closed curve with its osculating circle",
                 "#6b4226", "#38210f", "CURVATURE", "the osculating circle, r = 1/k")


def bell_curve():
    """Gauss's route to the normal distribution: noisy measurements, and the
    curve that least squares forces on their errors. Heights are negated
    because SVG's y axis points down."""
    rng = __import__("random").Random(20260907)

    def g(x):
        return math.exp(-x * x / 2)

    N, LO, HI = 400, -3.4, 3.4
    curve = [(LO + (HI - LO) * i / N, -g(LO + (HI - LO) * i / N)) for i in range(N + 1)]
    f = fit(curve + [(LO, 0.0), (HI, 0.0)], 158, 100)

    body = []
    ax0, ay0 = f((LO, 0.0))
    ax1, _ = f((HI, 0.0))
    body.append(f'<path d="M{ax0:.1f} {ay0:.1f} H{ax1:.1f}" stroke="#ffffff" '
                f'stroke-opacity="0.20" stroke-width="1"/>')
    for _ in range(170):                     # measurements scattered under the curve
        x = rng.gauss(0, 1)
        if not LO < x < HI:
            continue
        px, py = f((x, -g(x) * rng.random()))
        body.append(f'<circle cx="{px:.1f}" cy="{py:.1f}" r="2.6" '
                    f'fill="#ffffff" fill-opacity="0.38"/>')
    body.append(polyline([f(p) for p in curve], ACCENT, 3.0, 0.95))
    return frame("".join(body), "A Gaussian curve over scattered measurements",
                 "#7a3b52", "#3a1c28", "LEAST SQUARES", "e^(-x&#178;/2)")


FIGURES = {
    "winding-number": winding_number,
    "weierstrass": weierstrass,
    "penrose-tribar": penrose,
    "trefoil": trefoil,
    "icosahedron": icosahedron,
    "riemann-sqrt": riemann_sqrt,
    "potato-curvature": potato,
    "bell-curve": bell_curve,
}


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "monte-carlo.svg").write_text(monte_carlo())
    print("wrote monte-carlo.svg")
    for name, fn in FIGURES.items():
        (OUT / f"{name}.svg").write_text(fn())
        print("wrote", name + ".svg")
    for slug, title, kicker, c1, c2, deco in COVERS:
        fs = 54
        lines, n = tspans(title, fs)
        block = n * fs * 1.15                       # height of the title block
        ty = int(250 - block / 2 + fs * 0.35)       # title, centred on y=250
        svg = TPL.format(alt=esc(title), c1=c1, c2=c2, deco=deco, lines=lines,
                         fs=fs, ty=ty, ky=ty - fs - 14, kicker=esc(kicker))
        (OUT / f"{slug}.svg").write_text(svg)
        print("wrote", slug + ".svg")

if __name__ == "__main__":
    main()
