#!/usr/bin/env python3
"""AI-owned post-render step: writes meta-refresh stubs into docs/ for pages
whose URLs changed during the 2026 reorganisation, so old links keep working.

Never edit the generated stubs by hand. See CLAUDE.md.
"""
import html
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

# old path (relative to the site root)  ->  new path
REDIRECTS = {
    "notes.html": "projects/index.html",
    "rec letters.html": "rec-letters.html",
    "teaching statement.html": "teaching-statement.html",
}

STUB = """<!doctype html>
<!-- GENERATED by _scripts/write_redirects.py -- do not edit. See CLAUDE.md. -->
<html lang="en">
<head>
<meta charset="utf-8">
<title>Redirecting&hellip;</title>
<link rel="canonical" href="{target}">
<meta http-equiv="refresh" content="0; url={target}">
<meta name="robots" content="noindex">
</head>
<body>
<p>This page has moved to <a href="{target}">{target}</a>.</p>
</body>
</html>
"""


def main():
    if not DOCS.exists():
        raise SystemExit("write_redirects: docs/ not found; run a render first")
    for old, new in REDIRECTS.items():
        dest = DOCS / old
        # never clobber a page Quarto actually rendered
        if dest.exists() and "write_redirects.py" not in dest.read_text(
            encoding="utf-8", errors="ignore"
        )[:400]:
            print(f"write_redirects: skipping {old} (real page exists)")
            continue
        depth = old.count("/")
        target = ("../" * depth) + new
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(STUB.format(target=html.escape(target)), encoding="utf-8")
        print(f"write_redirects: {old} -> {target}")


if __name__ == "__main__":
    main()
