
## Complete List

| University | Course                                             | Years    | Avg # of students |                             |
|------------|----------------------------------------------------|----------|-------------------|-----------------------------|
| UWO        | Algebraic Topology                                 | 2021     | -                 | Math Grad                   |
|            | Discrete Structures for Engineering                | 2020     | -                 | -                           |
|            | Calculus II for Mathematical and Physical Sciences | 2020     | 150               | First year undergrad        |
|            | Calculus I for Mathematical and Physical Sciences  | 2019     | 176               | First year undergrad        |
|            | Topics in Category Theory                          | 2019     | 3                 | Math Grad                   |
| JHU        | Calculus II (For Biology and Social Science)       | 2019     | 5                 | First year undergrad        |
|            | Symmetries & Polynomials                           | 2018     | 10                | All years undergrad         |
|            | Honors Single Variable Calculus                    | 2017, 18 | 7                 | First year undergrad        |
|            | Differential Equations with Applications           | 2015, 17 | 11                | First year undergrad        |
|            | Hitchhiker’s Guide to Algebraic Topology           | 2017     | 11                | All years undergrad         |
|            | Online Linear Algebra                              | 2014     | 34                | All years undergrad         |
| Mathcamp   | See below                                          | 2015-19  | -                 | High school & middle school |

#### Calculus II for Mathematical and Physical Sciences (UWO, Winter 2020)
was a full semester 4 credit course with more than 300 students divided into 2 sections. I was the instructor for one of the sections and was solely responsible for making weekly WebWork homeworks and making exams along with the course coordinator. The class regularly met for 4 hours every week.

#### Calculus I for Mathematical and Physical Sciences (UWO, Fall 2019)
was a full semester course with more than 1000 students divided into 10 sections. I was the instructor for one of the sections and was solely responsible for making weekly WebWork homeworks and in-class quizzes. The class regularly met for 4 hours every week.

#### Topics in Category Theory (UWO, Fall 2019)
was a full semester reading course for math graduate students that I supervised.

#### Calculus II For Biology and Social Science (JHU, Summer 2019)
was a month long summer course which aims to cover semester-worth of material in one month. The class regularly met for 10 hours every week.

#### Differential Equations with Applications
#### Online Linear Algebra